//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Half_Chess__Winform_Client_
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGames
    {
        public int Id { get; set; }
        public int PlayerID { get; set; }
        public System.DateTime StartGameTime { get; set; }
        public double GameDuration { get; set; }
        public string GameMoves { get; set; }
        public string PlayerName { get; set; }
        public string Winner { get; set; }
        public bool IsWhite { get; set; }
    }
}
